version: '3.3'
services:

  eurekaservice:
    container_name: eureka-service
    build: EurekaService/
    hostname: localhost
    restart: always
    network_mode: host
    ports:
      - 8761:8761

  gatewayservice:
    container_name: gateway-service
    build: Gateway
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - eurekaservice
    ports:
      - 9000:9000

  mongodbservice:
    image: mongo:latest
    ports:
    - 27017:27017
    container_name: mongo-container
    network_mode: host
    hostname: localhost

  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"

  userauthenticaticationservice:
    container_name: user-authentication-service
    build: UserAuthenticationService/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mysqlservice
      - gatewayservice
      - eurekaservice
    ports:
      - 8082:8082

  userregisterservice:
    container_name: register
    build: UserRegisterService/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mongodbservice
      - gatewayservice
      - eurekaservice
      - mysqlservice
    ports:
      - 8086:8086

  taskservice:
    container_name: task-service
    build: TaskService/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mongodbservice
      - gatewayservice
      - eurekaservice
    ports:
      - 8085:8085

  organizationservice:
    container_name: organization-service
    build: OrganizationService/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mongodbservice
      - gatewayservice
      - eurekaservice
    ports:
      - 8088:8088

  archiveservice:
    container_name: archive-service
    build: ArchiveService/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mongodbservice
      - gatewayservice
      - eurekaservice
    ports:
      - 8087:8087