server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todoregisterdb
  application:
    name: register
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
