server:
 port: 9000
spring:
 application:
  name: api-gateway-service
 main:
  web-application-type: reactive
eureka:
 client:
  registerWithEureka: true
cloud:
 gateway:
  globalcors:
   corsConfigurations:
    '[/**]':
     allowedOrigins: "*"
     allowedMethods: "*"
     allowedHeaders: "*"