server:
  port: 8087
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todoregisterdb
  application:
    name: archive-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


