server:
 port: 8082
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/capstoneproject?useSSL=false&createDatabaseIfNotExist=true
  username: root
  password: Hero1997*
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL57Dialect
 application:
  name: user-authentication-service
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost